"""
Django settings for jartmanagement project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv
import os
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.getenv("JANART_DEBUG") == 'True')
from django.core.management.commands.runserver import Command as runserver
runserver.default_port = int(os.getenv("JANART_DEBUG_PORT", 8000))

# Application definition

INSTALLED_APPS = [
    'mediaserver.apps.MediaserverConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'allauth.socialaccount.providers.discord',

    'easy_thumbnails'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'jartmanagement.urls'

type TemplateConfig = dict[str, str | bool | list[str] | dict[str, list[str]]]

TEMPLATES: list[TemplateConfig] = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mediaserver.context_processors.brand_context',
            ],
        },
    },
]


AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = 'jartmanagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.getenv("JANART_TESTING_DB") == 'True':
    _db_type = 'sqlite3'
    _db_conf = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'django_test.db',
    }
else:
    db_name = os.getenv('POSTGRES_DATABASE')
    db_user = os.getenv('POSTGRES_USERNAME')
    db_pw = os.getenv('POSTGRES_PASSWORD')
    if db_name is None or db_user is None or db_pw is None:
        raise Exception("Postgres env variables missing")
    
    _db_type = 'postgresql'
    _db_conf: dict[str, str] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db_name,
        'USER': db_user,
        'PASSWORD': db_pw
    }

DATABASES = { 'default': _db_conf }
DATABASE_TYPE = _db_type


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'janart_cache_table',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Helsinki'

USE_I18N = True

USE_TZ = True


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.getenv("DJANGO_STATIC_ROOT")
STATICFILES_DIRS = [
     os.path.join('static/css'),
     os.path.join('static/js'),
     os.path.join('static/img'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.getenv("DJANGO_MEDIA_ROOT")
MEDIA_URL = 'media/'

type ThumbnailAliasOptions = dict[str, dict[str, dict[str, str | bool | tuple[int, int]]]]
THUMBNAIL_ALIASES: ThumbnailAliasOptions = {
    '': {
        '100': {'size': (100, 100), 'crop': True},
        '200': {'size': (200, 150), 'crop': 'smart'},
    }
}

SITE_ID=1

type SocialAccountProviderConfig = dict[str, list[str] | dict[str, str]]
SOCIALACCOUNT_PROVIDERS: dict[str, SocialAccountProviderConfig] = {
    'discord': {
        'APP': {
            'client_id': str(os.getenv("DISCORD_APPID")),
            'secret': str(os.getenv('DISCORD_SECRET'))
        },
        "SCOPE": [
            "identify"
        ]
    }
}

SOCIALACCOUNT_ONLY = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

LOGIN_URL = '/accounts/discord/login'
LOGIN_REDIRECT_URL = "/"

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

a_hosts_env = os.getenv("DJANGO_ALLOWED_HOSTS")
if DEBUG:
    _hosts = ['http://localhost', 'http://127.0.0.1']
if a_hosts_env is None:
    _hosts = []
else:
    _hosts: list[str] = []
    for host in a_hosts_env.split(','):
        if host.startswith('http://') or host.startswith('https://'):
            _hosts.append(host)
        elif host == 'localhost':
            _hosts.append('http://localhost')
        else:
            _hosts.append(f'https://{host}')

CSRF_TRUSTED_ORIGINS = _hosts

if DEBUG:
    _a_hosts = ['localhost', '127.0.0.1']
elif a_hosts_env is None:
    _a_hosts = []
else:
    _a_hosts = a_hosts_env.split(',')

ALLOWED_HOSTS = _a_hosts

REMOTE_TOKEN = os.getenv("REMOTE_TOKEN") # Token used for remote file submissions
REMOTE_USERNAME = os.getenv("REMOTE_USERNAME") # Username used for remote file submissions


# Style defaults from env
SITE_BRAND_NAME = os.getenv("SITE_BRAND_NAME", "Janart")
SITE_BRAND_DESC = os.getenv("SITE_BRAND_DESC", "The Joseph Anderson fanart Repository")
SITE_BRAND_EMBED = os.getenv("SITE_BRAND_EMBED", "Find all of your favorite chans and kuns here")
SITE_BRAND_PLEA = os.getenv("SITE_BRAND_PLEA", "You can submit fanart on the Discord server's #fanart channel!")
SITE_BRAND_COLOR = os.getenv("SITE_BRAND_COLOR", "#1b1111")
