# Generated by Django 5.0.1 on 2024-01-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0004_alter_tag_displayname_alter_tag_namespace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='author',
            new_name='title',
        ),
    ]
