# Generated by Django 5.0.1 on 2024-01-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0005_rename_author_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_count',
            field=models.IntegerField(default=0),
        ),
    ]
