# Generated by Django 5.0.1 on 2024-02-13 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0007_remove_media_author_tags_media_creator_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date uploaded'),
            preserve_default=False,
        ),
    ]
