# Generated by Django 5.1 on 2025-04-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0016_discordcreator_media_discord_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordcreator',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediaserver.tag'),
        ),
    ]
