# Generated by Django 5.0.1 on 2024-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=256)),
                ('namespace', models.CharField(max_length=256)),
                ('displayName', models.CharField(max_length=265)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='author_tags',
            field=models.ManyToManyField(blank=True, related_name='author_tags', to='mediaserver.tag'),
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='mediaserver.tag'),
        ),
    ]
