# Generated by Django 5.0.1 on 2024-01-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0002_tag_media_author_tags_media_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='displayName',
            field=models.CharField(blank=True, max_length=265),
        ),
        migrations.AlterField(
            model_name='tag',
            name='namespace',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
