# Generated by Django 5.0.1 on 2024-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0006_tag_tag_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='author_tags',
        ),
        migrations.AddField(
            model_name='media',
            name='creator_tags',
            field=models.ManyToManyField(blank=True, related_name='creator_tags', to='mediaserver.tag'),
        ),
    ]
