# Generated by Django 5.0.1 on 2024-03-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0008_media_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='media_items',
            field=models.ManyToManyField(related_name='media_gallery', through='mediaserver.GalleryOrder', to='mediaserver.media'),
        ),
    ]
