# Generated by Django 5.0.1 on 2024-03-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0010_copy_gallery_dates_to_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['namespace', 'tagname']},
        ),
    ]
