# Generated by Django 5.0.3 on 2024-07-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0011_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedMedia',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediaserver.media')),
                ('url', models.URLField()),
            ],
            bases=('mediaserver.media',),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
