# Generated by Django 5.1 on 2024-12-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0012_embeddedmedia_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
