# Generated by Django 5.1 on 2025-03-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0015_tag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaserver.tag')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='discord_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediaserver.discordcreator'),
        ),
    ]
