# Generated by Django 5.2 on 2025-04-15 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0017_alter_discordcreator_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordcreator',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assoc_discord', to='mediaserver.tag'),
        ),
        migrations.AlterField(
            model_name='media',
            name='discord_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assoc_media', to='mediaserver.discordcreator'),
        ),
    ]
