# Generated by Django 6.0.4 on 2026-05-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0018_alter_discordcreator_tag_alter_media_discord_creator'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Janart', max_length=256)),
                ('site_brand_color', models.CharField(default='#1b1111', max_length=256)),
                ('site_brand_description', models.TextField(default='The Joseph Anderson Fanart Repository')),
                ('site_brand_embed_description', models.TextField(default='Find all of your favorite chans here')),
                ('site_brand_plea', models.TextField(default='Want to see your fanart here? Art can be submitted in the JADS #share-stuff-you-made channel by sending it, right clicking on your message, and selecting Apps 🡒 Submit Stream Fanart')),
                ('site_brand_icon', models.ImageField(default=None, upload_to='site/')),
                ('site_brand_logo', models.ImageField(default=None, upload_to='site/')),
                ('holiday_mode', models.BooleanField(default=False)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.site')),
            ],
        ),
    ]
