# Generated by Django 6.0.4 on 2026-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0019_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site settings'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_brand_icon',
            field=models.ImageField(upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_brand_logo',
            field=models.ImageField(upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_brand_plea',
            field=models.TextField(default='Want to see your fanart here? Art can be submitted in the JADS #share-stuff-you-made channel by sending it, right clicking on your message, and selecting Apps 🡒 Submit Stream Fanart.'),
        ),
    ]
