# Generated by Django 6.0.4 on 2026-06-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0020_alter_gallery_options_alter_media_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='media',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='tag',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_brand_description',
            field=models.TextField(default='The Joseph Anderson fanart Repository'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_brand_embed_description',
            field=models.TextField(default='Find all of your favorite chans and kuns here'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_brand_plea',
            field=models.TextField(default="You can submit fanart on the Discord server's #fanart channel!"),
        ),
    ]
